config/routes.rb
Rails.application.routes.draw do
  resources :primes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/check', :controller=>'primes', :action=>'checkprime'
  post '/validate', :controller=>'primes', :action=>'isprime'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prime.rb
class Prime < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/primes_controller.rb
class PrimesController < ApplicationController
  before_action :set_prime, only: [:show, :edit, :update, :destroy]

  def isprime
    @input1 = params[:q]
    @p1 = PrimeChecker.new
    @result = @p1.is_prime?(@input1.to_i)
  end

  # GET /primes
  # GET /primes.json
  def index
    @primes = Prime.all
  end

  # GET /primes/1
  # GET /primes/1.json
  def show
  end

  # GET /primes/new
  def new
    @prime = Prime.new
  end

  # GET /primes/1/edit
  def edit
  end

  # POST /primes
  # POST /primes.json
  def create
    @prime = Prime.new(prime_params)

    respond_to do |format|
      if @prime.save
        format.html { redirect_to @prime, notice: 'Prime was successfully created.' }
        format.json { render :show, status: :created, location: @prime }
      else
        format.html { render :new }
        format.json { render json: @prime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /primes/1
  # PATCH/PUT /primes/1.json
  def update
    respond_to do |format|
      if @prime.update(prime_params)
        format.html { redirect_to @prime, notice: 'Prime was successfully updated.' }
        format.json { render :show, status: :ok, location: @prime }
      else
        format.html { render :edit }
        format.json { render json: @prime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /primes/1
  # DELETE /primes/1.json
  def destroy
    @prime.destroy
    respond_to do |format|
      format.html { redirect_to primes_url, notice: 'Prime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prime
      @prime = Prime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prime_params
      params.require(:prime).permit(:primenum)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/primes_helper.rb
module PrimesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrimeNumbers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/primes/_form.html.erb
<%= form_with(model: prime, local: true) do |form| %>
  <% if prime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prime.errors.count, "error") %> prohibited this prime from being saved:</h2>

      <ul>
      <% prime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :primenum %>
    <%= form.number_field :primenum, id: :prime_primenum %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/primes/checkprime.html.erb
<h1>Enter a number to check if it is Prime?</h1>
<%= form_tag("/validate", method: "post") do %>
    <%= label_tag(:q, "Search_for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
<% end %>

app/views/primes/edit.html.erb
<h1>Editing Prime</h1>

<%= render 'form', prime: @prime %>

<%= link_to 'Show', @prime %> |
<%= link_to 'Back', primes_path %>

app/views/primes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Primes</h1>

<table>
  <thead>
    <tr>
      <th>Primenum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @primes.each do |prime| %>
      <tr>
        <td><%= prime.primenum %></td>
        <td><%= link_to 'Show', prime %></td>
        <td><%= link_to 'Edit', edit_prime_path(prime) %></td>
        <td><%= link_to 'Destroy', prime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prime', new_prime_path %>

app/views/primes/isprime.html.erb
Prime Number Result<br>
<%= @input1 %> is <%= @result %>

app/views/primes/new.html.erb
<h1>New Prime</h1>

<%= render 'form', prime: @prime %>

<%= link_to 'Back', primes_path %>

app/views/primes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Primenum:</strong>
  <%= @prime.primenum %>
</p>

<%= link_to 'Edit', edit_prime_path(@prime) %> |
<%= link_to 'Back', primes_path %>